config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show index] do
    get 'search', on: :collection
    resource :profile, only: %i[new create edit update]
    resources :friendships, only: %i[index new create destroy]
  end

  post 'users/:id', to: 'profiles#create'
  get 'users/:id/profile', to: 'users#show'
  post 'users/:id/friendships', to: 'friendships#create'

  get 'search', to: 'users#search'

  resources :notifications, only: %i[index]
  delete 'notifications', to: 'notifications#destroy_multiple'

  resources :posts
  resources :comments, only: %i[index create destroy]
  resources :likes, only: %i[index create destroy]

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_one :notification, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :post_id, presence: true
  validates :user_id, presence: true
  validates :body, length: { in: 2..1_000 }

  default_scope { order(created_at: :ASC) }

  after_create { create_notification }
  before_destroy { notification&.destroy }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.includes(:comments).comments
  end

  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = @post.comments.build(body: comment_params[:body], user_id: current_user.id)
    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to request.referer }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if comment %>
  <div class="pb-2 grid" style="width: 610px" id="<%= "comment_#{comment.id}" %>">

    <div class="row-start-1 flex items-center pt-2">
      <div class="h-7 w-7 inline-block">
        <%= render partial: 'profiles/display_image', locals: { user: comment.user, size: :thumbnail } %>
      </div>
      
      <%= link_to comment.user.name, user_path(comment.user), data: { turbo_frame: "_top" }, class: "font-bold hover:text-sky-800 inline-block pl-3" %>
    </div>


    <div class="pt-1 pl-10 row-start-2 col-start-1 col-span-full" style="overflow-wrap: break-word; word-break: break-word;">
      <%= sanitize(comment.body.strip.gsub(/\n/, "<br/>")) %>
    </div>

    <%= turbo_frame_tag "like_#{comment.post.id}", class: "row-start-3 col-start-1 pl-10 pt-2" do %>
      <% if comment.likes.any? { |like| like.user_id == current_user.id } %>
        <%= render partial: 'likes/unlike', locals: {resource: comment } %>
      <% else %>
        <%= render partial: 'likes/like', locals: { resource: comment } %>
      <% end %>
    <% end %>

    <% if comment.user == current_user %>
 	    <%= link_to image_tag("icons/delete_outline.png"), comment_path(comment.id), title: 'Delete Comment', data: { turbo_method: :delete }, class: "invert brightness-50 hover:brightness-100 row-start-3 justify-self-center" %>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="comment">
  <%= form_with model: Comment,
                  data: { controller: 'input', action: 'turbo:submit-end->input#clear' } do |form| %>
    <%= form.text_area :body, size: '60X10', placeholder: 'Leave a comment', class: "text-sm align-middle p-2 max-w-full outline-none focus:border-2 focus:border-sky-800" %>
    <%= form.hidden_field :post_id, value: post.id %>
    <%= form.submit 'Add', class: "border-solid border-2 border-stone-200 p-0.5 ml-2 bg-stone-200 hover:bg-amber-300 hover:cursor-pointer rounded-sm" %>
  <% end %>
</div>

app/views/comments/_preview.html.erb
<% post.comments.includes(:user).last(3).each do |comment| %>
  <% if comment %>
    <%# adding inline style because Tailwind width isnt working here. %>
    <div class="grid" style="width: 610px" id="<%= "comment_#{comment.id}" %>">

      <div class="row-start-1 flex items-center pt-2">
        <div class="h-7 w-7 inline-block">
          <%= render partial: 'profiles/display_image', locals: { user: comment.user, size: :thumbnail } %>
        </div>
  
        <%= link_to comment.user.name, user_path(comment.user), data: { turbo_frame: "_top" }, class: "font-bold hover:text-sky-800 inline-block pl-3" %>
      </div>

      <%# adding inline style because Tailwind break word isnt working here. %>
      <div class="pt-1 pl-10 row-start-2 col-start-1 col-span-full" style="overflow-wrap: break-word; word-break: break-word;">
        <%= sanitize(comment.body.strip.gsub(/\n/, "<br/>")) %>
      </div>

      <%= turbo_frame_tag "like_#{post.id}", class: "row-start-3 col-start-1 pl-10 pt-2" do %>
        <% if comment.likes.any? { |like| like.user_id == current_user.id } %>
          <%= render partial: 'likes/unlike', locals: {resource: comment } %>
        <% else %>
          <%= render partial: 'likes/like', locals: { resource: comment } %>
        <% end %>
      <% end %>

      <% if comment.user == current_user %>
 	      <%= link_to image_tag("icons/delete_outline.png"), comment_path(comment.id), title: 'Delete Comment', data: { turbo_method: :delete }, class: "invert brightness-50 hover:brightness-100 row-start-3 justify-self-center" %>
      <% end %>
    </div>
  <% end %>
<% end %>

<% @num_comments = post.comments.size %>
<% if @num_comments > 3 %>
  <div class="row-start-4 pl-3 py-1 underline decoration-sky-800 text-sky-800">
    <%= link_to "#{post.comments.size - 3} more comment#{'s' if @num_comments > 4}.", post_path(post), data: {turbo_frame: "_top" } %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%# if on the posts show page %>
<% if URI(request.referer).path.include?(@post.id.to_s)  %>
  <%= turbo_stream.append 'comment' do %>
      <%= render partial: 'comment', locals: { comment: @comment } %>
  <% end %>
<%# otherwise on the post index or user show page %>
<% else %>
  <%= turbo_stream.update "post_#{@post.id}" do %>
    <%= render partial: 'preview', locals: { post: @post} %>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment_#{@comment.id}" %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
  <%= comment.user.name %>
  <%= comment.body  %>
  <br>
<% end %>