config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show index] do
    get 'search', on: :collection
    resource :profile, only: %i[new create edit update]
    resources :friendships, only: %i[index new create destroy]
  end

  post 'users/:id', to: 'profiles#create'
  get 'users/:id/profile', to: 'users#show'
  post 'users/:id/friendships', to: 'friendships#create'

  get 'search', to: 'users#search'

  resources :notifications, only: %i[index]
  delete 'notifications', to: 'notifications#destroy_multiple'

  resources :posts
  resources :comments, only: %i[index create destroy]
  resources :likes, only: %i[index create destroy]

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :friendship, optional: true
  belongs_to :like, optional: true
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @friend_requests = User.friend_requests(current_user)
    @profile_posts = User.profile_posts(current_user)
    @comments = User.comments(current_user)
    @likes = User.likes(current_user)
  end

  def destroy_multiple
    params[:notification].each_pair do |k, v|
      Notification.destroy(k) if v == '1'
    end
    redirect_to notifications_path
  end
end

app/views/notifications/index.html.erb
<div class="mt-10 grid justify-items-center">
  <div class="shadow-inner p-4">
    <div class="grid justify-items-center">
      <h4 class="text-lg font-bold pb-4">Notifications</h4>
      <%= form_with model: Notification, method: :delete do |form| %>
          <% if @profile_posts && !@profile_posts.empty? %>
              <% @profile_posts.each do |post| %>
                <div class="flex flex-rows gap-4 py-1 items-center">
                  <%= form.check_box post.notification.id %>
                  <div class="h-10 w-10">
                    <%= render partial: 'profiles/display_image', locals: { user: post.user, size: :thumbnail } %>
                  </div>
                  <div class="flex gap-2">
                    <%= link_to post.user.name, user_path(post.user), class: "hover:text-sky-800 font-bold" %>   
                        posted on your profile. 
                  </div>
                  <%= link_to "View", post_path(post), class: "underline decoration-sky-800 text-sky-800 text-sm" %>
                </div>
            <% end %>
          <% end %>
    
        <div>
          <% if @comments && !@comments.empty? %>
            <% @comments.each do |comment| %>
              <div class="flex flex-rows gap-4 py-1 items-center">
                <%= form.check_box comment.notification.id %>
                <div class="h-10 w-10">
                  <%= render partial: 'profiles/display_image', locals: { user: comment.user, size: :thumbnail } %>
                </div>
                <div class="flex gap-2">
                	<%= link_to comment.user.name, user_path(comment.user), class: "hover:text-sky-800 font-bold" %>
                	  commented on your post.
                </div>
                <%= link_to "View", post_path(comment.post), class: "underline decoration-sky-800 text-sky-800 text-sm" %>
              </div>
            <% end %>
          <% end %>
        </div>
    
        
          <% if @likes && !@likes.empty? %>
            <% @likes.each do |like| %>
              <div class="flex flex-rows gap-4 py-1 items-center">
                <%= form.check_box like.notification.id %>
                <div class="h-10 w-10">
                  <%= render partial: 'profiles/display_image', locals: { user: like.user, size: :thumbnail } %>
                </div>
                <div class="flex gap-2">
                  <%= link_to like.user.name, user_path(like.user), class: "hover:text-sky-800 font-bold" %>
                    likes your
                  <% if like.comment %>
                    <%= 'comment.' %>
                  <% else %>
                    <%= 'post.' %>
                  <% end %>
                </div>
                <%= link_to "View", post_path(like.post || like.comment.post), class: "underline decoration-sky-800 text-sky-800 text-sm"%>
              </div>
            <% end %>
          <% end %>
       
        <% if @profile_posts.empty? && @likes.empty? && @comments.empty?%>
          <h5 class="text-sm">Nothing to see here. Check back later.</h5>
        <% else %>
          <%= form.submit 'Delete selected notifications', class: "border-solid border-2 border-stone-200 p-0.5 ml-2 mt-4 bg-stone-200 hover:bg-amber-300 hover:cursor-pointer rounded-sm" %>
        <% end %>
      <% end %>
    
    </div>
  
    <div class="grid">
      <h4 class="text-lg font-bold mt-8 pb-4 justify-self-center">Friend Requests</h4>
        <% @friend_requests.each do |request| %>

            <%= turbo_frame_tag "incoming_request_#{request.user.id}" do %>

              <div class="flex flex-row gap-4 py-1 items-center">
                <div class="h-10 w-10">
                  <%= render partial: 'profiles/display_image', locals: { user: request.user, size: :thumbnail } %>
                </div>

                <%= link_to request.user.name, user_path(request.user), class: "hover:text-sky-800 font-bold", data: { turbo_frame: "_top" } %>

                 <%= link_to "Accept Request", user_friendships_path(current_user, type: :accept_request, requester: request.user), data: { turbo_method: :post }, class: "underline decoration-sky-800 text-sky-800 text-sm"  %>

                <%= link_to "Deny Request", user_friendship_path(current_user, request.id, type: :deny_request), data: { turbo_method: :delete }, class: "underline decoration-sky-800 text-sky-800 text-sm"  %>
              
              </div>
            <% end %>
        <% end %>

        <% if @friend_requests.empty? %>
          <h5 class="text-sm">Nothing to see here. Check back later.</h5>
        <% end %>
    </div>
  </div>
</div>