config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show index] do
    get 'search', on: :collection
    resource :profile, only: %i[new create edit update]
    resources :friendships, only: %i[index new create destroy]
  end

  post 'users/:id', to: 'profiles#create'
  get 'users/:id/profile', to: 'users#show'
  post 'users/:id/friendships', to: 'friendships#create'

  get 'search', to: 'users#search'

  resources :notifications, only: %i[index]
  delete 'notifications', to: 'notifications#destroy_multiple'

  resources :posts
  resources :comments, only: %i[index create destroy]
  resources :likes, only: %i[index create destroy]

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  has_one :notification, dependent: :destroy
  validates :user_id, presence: true
  validates :comment_id, presence: true, unless: :post_id
  validates :post_id, presence: true, unless: :comment_id

  after_create { create_notification }
  before_destroy { notification&.destroy }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # shows all likes on a specific post or comment
  def index
    klass = params[:resource][:type].constantize
    resource = klass.find(params[:resource][:id])
    @likes = resource.likes
  end

  def create
    klass = params[:resource][:type]
    column = "#{klass.downcase}_id".to_sym
    foreign_key = { column => params[:resource][:id] }

    @like = current_user.likes.build(foreign_key)
    @like.save!

    resource = klass.constantize.find(params[:resource][:id])
    render partial: 'unlike', locals: { resource: resource }
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    @comment = @like.comment
    resource = @post || @comment
    @like.destroy
    render partial: 'like', locals: { resource: resource }
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= turbo_frame_tag "like_#{resource.id}", class: "flex items-center " do %>
  <% likes = resource.likes.count %>
  <% if likes > 0 %>
    <div class="inline-block h-5 text-neutral-500 text-sm">
      <%= link_to likes, likes_path(resource: {type: resource.class, id: resource.id}), class: "underline decoration-sky-800 text-sky-800", data: { turbo_frame: "_top" } %> 
      <%= 'person' if likes == 1 %>  
      <%= 'people' if likes > 1 %>
      like<%= 's' if likes == 1 %> this.&nbsp;&nbsp;
    </div>
  <% else %>
    <div class="inline-block h-5 text-neutral-500 text-sm">Be the first to like this!&nbsp;&nbsp;</div>
  <% end %>
  <div class="inline-block">
    <%= link_to image_tag("icons/like_outline.png", class: "h-5 w-5"), likes_path(resource: {type: resource.class, id: resource.id }), data: { turbo_method: :post }, title: 'Like', class: "invert brightness-50 hover:brightness-100 " %>
  </div>
<% end %>

app/views/likes/_unlike.html.erb
<%= turbo_frame_tag "like_#{resource.id}", class: "flex items-center" do %>
  
  <% other_likes = resource.likes.count - 1 %>
  <% if other_likes > 0 %>
    <div class="inline-block h-5 text-neutral-500 text-sm">
      You and <%= link_to other_likes, likes_path(resource: {type: resource.class, id: resource.id}), class: "underline decoration-sky-800 text-sky-800", data: { turbo_frame: "_top" } %> other<%= 's' if other_likes > 1 %> like this!&nbsp;&nbsp;
    </div>
  <% else %>
    <div class="inline-block h-5 text-neutral-500 text-sm">You like this!&nbsp;&nbsp;</div>
  <% end %>

  <div class="inline-block">
    <%= link_to image_tag("icons/unlike_outline.png", class: "h-5 w-5"), like_path(Like.find_by(user_id: current_user.id, "#{resource.class}_id".downcase.to_sym => resource.id )), data: { turbo_method: :delete }, title: 'Unlike', class: "invert brightness-50 hover:brightness-100" %>
  </div>
<% end %>

app/views/likes/index.html.erb
<div class="grid justify-items-center mt-10">
  <div class="bg-stone-100 shadow-inner px-8 py-4">
    <div class="flex flex-col gap-4">
      <%= link_to "back", :back, class: "underline decoration-sky-800 text-sky-800"  %>
      <h4 class="self-center text-lg font-bold pb-4">Likes</h4>
    </div>
    
    <div>
      <% @likes.each do |like| %>
        <div class="flex gap-3 pb-3">
          <div class="h-10 w-10">
            <%= render partial: 'profiles/display_image', locals: { user: like.user, size: :thumbnail } %>
          </div>
          <%= link_to like.user.name, user_path(like.user), class: "self-center hover:text-sky-800" %>
        </div>
      <% end %>
    </div>
  </div>
</div>