config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[show index] do
    get 'search', on: :collection
    resource :profile, only: %i[new create edit update]
    resources :friendships, only: %i[index new create destroy]
  end

  post 'users/:id', to: 'profiles#create'
  get 'users/:id/profile', to: 'users#show'
  post 'users/:id/friendships', to: 'friendships#create'

  get 'search', to: 'users#search'

  resources :notifications, only: %i[index]
  delete 'notifications', to: 'notifications#destroy_multiple'

  resources :posts
  resources :comments, only: %i[index create destroy]
  resources :likes, only: %i[index create destroy]

  devise_scope :user do
    root 'devise/sessions#new'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeoplePages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="m-5">
    <% if user_signed_in?  %>
      <nav class="grid grid-cols-9 gap-4 items-center bg-stone-200">

        <div class="justify-self-center p-2 hover:rounded-b-lg hover:bg-amber-300">
          <%= link_to image_tag("people_pages.svg", class: "h-8"), posts_path  %>
        </div>
        <div class="h-full flex items-center justify-self-start p-2 hover:rounded-b-lg hover:bg-amber-300" >
          <%= link_to "Find Friends", users_path %>
        </div>
        <div class="h-full flex items-center col-start-4 justify-self-end p-2 hover:rounded-b-lg hover:bg-amber-300">
          <%= link_to current_user.name, user_profile_path(current_user) %>
        </div>
        <div class="h-full flex items-center col-start-5 justify-self-center p-2 hover:rounded-b-lg hover:bg-amber-300">
          <%= link_to "Friends", user_friendships_path(current_user) %>
        </div>
        <div class="h-full flex items-center col-start-6 col-span-2 justify-self-start p-2 hover:rounded-b-lg hover:bg-amber-300">
          <%= link_to "Notifications", notifications_path %>
        </div>
        <div class="h-full flex items-center justify-self-center col-start-9 p-2 hover:rounded-b-lg hover:bg-amber-300">
          <%= link_to "Sign Out", destroy_user_session_path %>
        </div>

      </nav>
    <% end %>

    <p class="text-lg text-green-700"><%= notice %></p>
    <p class="text-lg text-red-700"><%= alert %></p>

    <%= yield %>
  </body>
</html>